### ISSUE TITLE
Updating gym to gymnasium and cleaning some imports

### ISSUE THREAD

**Issue by mikelitu** [ScheiklP/sofa_env#10]
Hello,

I am working a lot with Sofa in the last few years for my PhD and I have found this repository as @ScheiklP mentioned one code snapshot from it when I was struggling with a grasping simulation. I have to say that this repository is really impressive and I would be really interested to use some of the environments to train some DNN for my PhD and add some extra functionalities along with my work. 

However, I came across some problem when trying to install the python package on my computer. I found the error was coming from the *Gym* package. As I could read at the official repository from **OpenAI** about [Gym](https://github.com/openai/gym), they stopped maintainance on this repository on **2021**. The development was moved to [**Gymnasium**](https://github.com/Farama-Foundation/Gymnasium) and now the recommended form of use is `import gymnasium as gym`. I think it will be good for new users to have this updated on the main branch. Do you want me to submit a pull request with the necessary changes? 

Regards,
Mikel

**Comment by ScheiklP** [comment]
Hi @mikelitu,
thanks a lot for your kind words! :)

I actually have a local branch where I already updated to gymnasium.
I just did not have the time yet to properly review and push it.

I will try to do that in the coming weeks and would be very grateful, if you could review the PR. Would you be interested in that?

Cheers,
Paul

**Comment by mikelitu** [comment]
Hi @ScheiklP,

Thank you for the fast respond. Sure, happy to review the PR once you are done with it.

Best,
Mikel

**Comment by ScheiklP** [comment]
Hi @mikelitu,
from a first check, that went easier than expected.
Could you head over to the PR and give it a test drive?

Cheers,
Paul
