### ISSUE TITLE
sofa_env test question

### ISSUE THREAD

**Issue by Fhy0720** [ScheiklP/sofa_env#15]
Hi, I met a problem while testing the installation `python3 sofa_env/scenes/controllable_object_example/controllable_env.py`
And I got out put like this
```
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: /home/yhf/sofa/build/install
---------------------------------------
Traceback (most recent call last):
  File "/home/yhf/sofa/sofa_env/sofa_env/scenes/controllable_object_example/controllable_env.py", line 65, in <module>
    env.reset()
  File "/home/yhf/sofa/sofa_env/sofa_env/scenes/controllable_object_example/controllable_env.py", line 53, in reset
    return super().reset(seed)
  File "/home/yhf/sofa/sofa_env/sofa_env/base.py", line 206, in reset
    self._init_sim()
  File "/home/yhf/sofa/sofa_env/sofa_env/base.py", line 229, in _init_sim
    self.sofa = importlib.import_module("Sofa")
  File "/home/yhf/anaconda3/envs/sofa_try/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/yhf/anaconda3/envs/sofa_try/lib/python3.9/site-packages/Sofa/__init__.py", line 140, in <module>
    import Sofa.Helper
ModuleNotFoundError: No module named 'Sofa.Helper'
```
What should I do to solve this problem? Thank you.

**Comment by ScheiklP** [comment]
Hi @DISCORDzzz ,
that looks like the installation of SOFA did not work correctly.

Could you post the output of `ls /home/yhf/anaconda3/envs/sofa_try/lib/python3.9/site-packages/Sofa`?

**Comment by Fhy0720** [comment]
Thanks for your reply! Here is the content in Sofa:
![2023-11-24 17-17-10 的屏幕截图](https://github.com/ScheiklP/sofa_env/assets/128584832/c096da8b-fd54-443f-ba70-a9ac6ce3c551)

**Comment by ScheiklP** [comment]
Hi @DISCORDzzz ,
it seems like you have SOFA that was compiled with python version 3.7 (the 37m in the library file names), but then linked it to a conda environment with python 3.9.
I guess that you downloaded the precompiled version of SOFA from SOFA's website, right?
They are currently working on providing precompiled versions with a newer python version.
Until then, I am afraid you will have to compile SOFA yourself.
You can find instructions on how to do that [here](https://scheiklp.github.io/sofa_env/setting_up_sofa.html)

**Comment by DISCORDzzz** [comment]
Thanks for your reply!
Actually, I just install sofa through the instructions here[https://github.com/ScheiklP/sofa_env/blob/main/docs/source/setting_up_sofa.rst](here), So I think it may not the problem. My problem is still not solved. Can you give me some further advice? Thank you!

**Comment by Fhy0720** [comment]
Thanks for your reply!
Actually, I just install sofa through the instructions in Github, which is almost the same as the link you provided. So I think it may not the problem. My problem is still not solved. 
As you mentioned, there are some file names with 37m, but I installed all the environment in anaconda with python=3.9, so I am not sure what happened.
Can you give me some further advice? Thank you!

**Comment by ScheiklP** [comment]
*Almost* the same is the problem most of the times ;).
Did you set the python related flags in cmake?

```
-DPython_EXECUTABLE=$PYTHON_EXE \
-DPython_ROOT_DIR=$PYTHON_ROOT_DIR \
-DSP3_LINK_TO_USER_SITE=ON \
-DSP3_PYTHON_PACKAGES_LINK_DIRECTORY=$PYTHON_PKG_PATH \
```

The env variables should be set like described [here](https://scheiklp.github.io/sofa_env/setting_up_sofa.html#environment-variables-for-building-sofa)

**Comment by Fhy0720** [comment]
Thanks for your reply! 
As you say, I re-install the environment again, and while running the test `python3 sofa_env/scenes/controllable_object_example/controllable_env.py`, I do not face the problem above.
Now the output looks like below:
```
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: /home/hfyu/sofa/build/install
---------------------------------------
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.LinearSolver.Iterative.so
[DEPRECATED] [SofaEngine] SofaEngine is deprecated. It will be removed at v23.06. Use Sofa.Component.Engine.Select instead.
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Engine.Select.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/collections/SofaEngine/lib/libSofaEngine.so
[DEPRECATED] [SofaBoundaryCondition] SofaBoundaryCondition is deprecated. It will be removed at v23.06. You may use Sofa.Component.Constraint.Projective and Sofa.Component.MechanicalLoad instead.
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Constraint.Projective.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.MechanicalLoad.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/collections/SofaBoundaryCondition/lib/libSofaBoundaryCondition.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Collision.Detection.Algorithm.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Mapping.Linear.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Topology.Container.Grid.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Constraint.Lagrangian.Solver.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.AnimationLoop.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Topology.Mapping.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Collision.Geometry.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Topology.Container.Constant.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.SceneUtility.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.SolidMechanics.Spring.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.IO.Mesh.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.GL.Component.Rendering3D.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.LinearSolver.Direct.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.ODESolver.Forward.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.StateContainer.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/plugins/ArticulatedSystemPlugin/lib/libArticulatedSystemPlugin.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Constraint.Lagrangian.Correction.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Collision.Response.Contact.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Visual.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Setting.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.ODESolver.Backward.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.SolidMechanics.FEM.Elastic.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Topology.Container.Dynamic.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.GL.Component.Shader.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Mass.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Mapping.NonLinear.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Collision.Detection.Intersection.so
[INFO]    [PluginManager] Loaded plugin: /home/hfyu/sofa/build/install/lib/libSofa.Component.Constraint.Lagrangian.Model.so
[WARNING] [MechanicalObject(unnamed)] Could not read value for data field showColor: 255 0 255 
[WARNING] [BoxROI(BoxROI)] No rest position yet defined. Box might not work properly. 
This may be caused by an early call of init() on the box before  
the mesh or the MechanicalObject of the node was initialized too
[WARNING] [MeshOBJLoader(unnamed)] Could not read value for data field handleSeams: None
[WARNING] [InteractiveCamera(camera)] Too many missing parameters ; taking default ...
[ERROR]   [SofaRuntime] NoSuchDisplayException: Cannot connect to "None"
Traceback (most recent call last):
  File "/home/hfyu/sofa/sofa_env/sofa_env/scenes/controllable_object_example/controllable_env.py", line 65, in <module>
    env.reset()
  File "/home/hfyu/sofa/sofa_env/sofa_env/scenes/controllable_object_example/controllable_env.py", line 53, in reset
    return super().reset(seed)
  File "/home/hfyu/sofa/sofa_env/sofa_env/base.py", line 206, in reset
    self._init_sim()
  File "/home/hfyu/sofa/sofa_env/sofa_env/base.py", line 299, in _init_sim
    self._init_pyglet_window()
  File "/home/hfyu/sofa/sofa_env/sofa_env/base.py", line 342, in _init_pyglet_window
    display = self.pyglet.canvas.get_display()
  File "/home/hfyu/anaconda3/envs/sofa/lib/python3.9/site-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/home/hfyu/anaconda3/envs/sofa/lib/python3.9/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
```
It seems that the environment is normal, right? I think it may because I used vscode on my laptop to connect to the remote server to run the code. What should I do to solve the problme now?
Thank you!

**Comment by ScheiklP** [comment]
Hi @DISCORDzzz,
yes, that looks good.

Could you try to set `render_mode=RenderMode.REMOTE`?

**Comment by DISCORDzzz** [comment]
Thanks for your reply. I tried to set `render_mode: RenderMode = RenderMode.REMOTE` in `controllable_env.py`, but the result did not change.
![Uploading 微信截图_20231201163323.png…]()

**Comment by DISCORDzzz** [comment]
@ScheiklP Thanks for your reply. I tried to set `render_mode:` RenderMode = `RenderMode.REMOTE` in `controllable_env.py`, but the result did not change.

**Comment by Fhy0720** [comment]
@ScheiklP Thanks for your reply. I tried to set `render_mode: RenderMode = RenderMode.REMOTE` in `controllable_env.py`, but the result did not change.

**Comment by ScheiklP** [comment]
Hi @DISCORDzzz ,
Did you set that in [Line 62](https://github.com/ScheiklP/sofa_env_devel/blob/main/sofa_env/scenes/controllable_object_example/controllable_env.py#L62) or in [Line 15](https://github.com/ScheiklP/sofa_env_devel/blob/main/sofa_env/scenes/controllable_object_example/controllable_env.py#L15)?

**Comment by Fhy0720** [comment]
I set in Line 15

**Comment by ScheiklP** [comment]
Line 15 only declares, that the classe's init function accepts a parameter named `render_mode` and sets its default to `RenderMode.X`, if the user does not pass it during instantiation.
Down in the main part, the class is actually instantiated and Line 62 passes the actual value for `render_mode`.
So please change it in Line 62. :)

**Comment by Fhy0720** [comment]
Yes, you are right. I set `render_mode` in Lin62 now, but the problem still remains. T-T

**Comment by ScheiklP** [comment]
How about `RenderMode.HEADLESS`?

**Comment by Fhy0720** [comment]
@ScheiklP, It still does not work.  (T_T
I check the issue `NoSuchDisplayException: Cannot connect to "None"` on the Internet, some answers said that this error is usually caused when running the pyglet application in an environment without a monitor. I think this is very possible? I used the company's remote server and was missing the relevant libraries on my laptop to observe. Do you think this is a possible cause of the problem? How should I proceed? Thanks!

**Comment by ScheiklP** [comment]
Hi @DISCORDzzz ,
by setting `RenderMode.HEADLESS` we tell pyglet to use an EGL backend for headless rendering.
That is what I use to run sofa_env on clusters that do not have displays.

Sadly, without having access to your system, I am not sure how much I can help there....

Could you try running a minimal EGL-based example?
For example https://pyrender.readthedocs.io/en/latest/examples/offscreen.html with the egl option.

**Comment by ScheiklP** [comment]
Hi @DISCORDzzz ,
do you have any updates?

Cheers,
Paul

**Comment by Fhy0720** [comment]
sorry for late reply. I think I can solve this problem now. I can get train info in terminal now. Although there is still no window, I think I get the way.

**Comment by ScheiklP** [comment]
Hi @DISCORDzzz ,
no worries.
Ok cool! Let me know if you find out more! :)
