### ISSUE TITLE
CANNOT build SOFA

### ISSUE THREAD

**Issue by kanta-lee** [ScheiklP/sofa_env#16]
I'm installing the SOFA environment following this link https://github.com/ScheiklP/sofa_env/blob/d0d197d4bda74338e8b6aa1e5a72a9c715f7f73e/docs/source/setting_up_sofa.rst

Follow the instructions from top to bottom until the build SOFA in the Compile SOFA part. I received a thousand lines of error.

---------------------------------------------

### Environment

**Context**

- System: Ubuntu 18.04.5 LTS
- Version of SOFA: master branch at commit d0d197d

**Command called**
```txt
cmake --build $FOLDER_TARGET -j --target install
```

I will show you a first few lines of the error messages.

```txt
In file included from /bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.cpp:22:0:
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:28:23: error: variable 'sofa::helper::visual::SOFA_EXPORT_DYNAMIC_LIBRARY sofa::helper::visual::Transformation' has initializer but incomplete type
 class SOFA_HELPER_API Transformation
                       ^~~~~~~~~~~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:30:1: error: expected primary-expression before 'public'
 public:
 ^~~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:30:1: error: expected '}' before 'public'
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:30:1: error: expected ',' or ';' before 'public'
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:32:5: error: 'SReal' does not name a type
     SReal   scale[3];
     ^~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:33:5: error: 'SReal' does not name a type
     SReal   rotation[4][4];
     ^~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:34:5: error: 'SReal' does not name a type
     SReal   objectCenter[3];
     ^~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:36:21: error: expected constructor, destructor, or type conversion before ';' token
     Transformation();
                     ^
```

**Comment by kanta-lee** [comment]
By the way in the install build dependencies which are located at the very top of the instruction link, Are there equivalence libraries in the conda environment? (conda install ...)
```bash
sudo apt -y install build-essential software-properties-common python3-software-properties
sudo apt -y install libboost-all-dev
sudo apt -y install libpng-dev libjpeg-dev libtiff-dev libglew-dev zlib1g-dev
sudo apt -y install libeigen3-dev
sudo apt -y install libcanberra-gtk-module libcanberra-gtk3-module
sudo apt -y install qt5-default
```
I happened to be using my school virtual machine, and I am not allowed to use sudo to install which makes things very troublesome. Thank you in advance!

**Comment by ScheiklP** [comment]
Hi @KantaphatLeelakunwet ,
which commit of SOFA are you using? The commit hash that you posted belongs to sofa_env, not SOFA.

You should be able to find equivalents for most packages, yes.
But compiling from source is also an option. ;)

**Comment by kanta-lee** [comment]
<img width="1415" alt="image" src="https://github.com/ScheiklP/sofa_env/assets/140193594/3c06a5fe-3e0c-4a3d-bdb5-22e9fe83fc28">

---------------

<img width="829" alt="image" src="https://github.com/ScheiklP/sofa_env/assets/140193594/f954d268-8b79-435d-a225-ad01f6fbe520">

---------------

The error messages shown above appeared when I was running Cmake. Will it be a problem?

**Comment by kanta-lee** [comment]
```cmake --build $FOLDER_TARGET -j --target install```

When I ran the above command, I somehow got stuck halfway. Below is the error message.

```
[ 70%] Built target Sofa.Component.Mapping.Linear
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
```

Do you know where the problem is? 
Thanks in advance.

**Comment by ScheiklP** [comment]
Hi @KantaphatLeelakunwet,
the `-j` flag in the command will tell cmake to build with multiple cores -> parallel execution.
The actuall error message should be a bit further up (a few lines above the `[70%] ...`.

Again, which version of SOFA are you using?

**Comment by kanta-lee** [comment]
I want to use LapGym. Is this what you want to ask?

**Comment by ScheiklP** [comment]
Hi @KantaphatLeelakunwet ,
`sofa_env` uses [SOFA](https://www.sofa-framework.org/) as a physics engine.
You are currently trying to compile SOFA, but encounter some errors.
My question is what commit of the [SOFA Repository](https://github.com/sofa-framework/sofa) you are using.

Also, when the build fails, could you scroll up a bit to send me the actual error that led to the failed command?

**Comment by kanta-lee** [comment]
I think it's 5a73716

<img width="1426" alt="image" src="https://github.com/ScheiklP/sofa_env/assets/140193594/22cd5d5a-e2a3-402c-b2f1-620ef05b2596">

**Comment by ScheiklP** [comment]
That is the subproject `SofaPython3`.
The SOFA commit should be the one from `git checkout v23.06` is that correct?

**Comment by kanta-lee** [comment]
That's right. I just follow everything from the link.

**Comment by ScheiklP** [comment]
And were you able to install all the build dependencies?

**Comment by kanta-lee** [comment]
Yes, I installed the equivalent packages already. However, when I ran CMake I received this message.

<img width="1426" alt="image" src="https://github.com/ScheiklP/sofa_env/assets/140193594/8225fe32-cb41-407b-bfcc-04a2c478d5f2">

**Comment by ScheiklP** [comment]
And the error is still
```
In file included from /bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.cpp:22:0:
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:28:23: error: variable 'sofa::helper::visual::SOFA_EXPORT_DYNAMIC_LIBRARY sofa::helper::visual::Transformation' has initializer but incomplete type
 class SOFA_HELPER_API Transformation
                       ^~~~~~~~~~~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:30:1: error: expected primary-expression before 'public'
 public:
 ^~~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:30:1: error: expected '}' before 'public'
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:30:1: error: expected ',' or ';' before 'public'
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:32:5: error: 'SReal' does not name a type
     SReal   scale[3];
     ^~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:33:5: error: 'SReal' does not name a type
     SReal   rotation[4][4];
     ^~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:34:5: error: 'SReal' does not name a type
     SReal   objectCenter[3];
     ^~~~~
/bigdata/users/kleelakunwet/sofa/src/Sofa/framework/Helper/src/sofa/helper/visual/Transformation.h:36:21: error: expected constructor, destructor, or type conversion before ';' token
     Transformation();
                     ^
```

I am asking again, because it seems like you have switched machines (different path to your home directory).

**Comment by kanta-lee** [comment]
Oh right, I'm using the school cluster and I am required to change the directory so everything now is moved to /bd_targaryen/users/...

**Comment by kanta-lee** [comment]
The problem right now is at this line.

<img width="645" alt="image" src="https://github.com/ScheiklP/sofa_env/assets/140193594/e95f21aa-8424-4609-a105-3c36d1079645">

<img width="1426" alt="image" src="https://github.com/ScheiklP/sofa_env/assets/140193594/4ee335da-a764-49a4-9b56-086a9266d802">

**Comment by ScheiklP** [comment]
I have never seen that error before. :(
Sadly I do not have access to an machine running Ubuntu 18.04 right now.
Since the error is a problem with SOFA, and not `sofa_env`, would it be possible for you to again post your question [here](https://github.com/sofa-framework/sofa/issues)?

**Comment by kanta-lee** [comment]
Sure, thank you for the help!

**Comment by ScheiklP** [comment]
Thank you! :)
