### ISSUE TITLE
Error File Repository

### ISSUE THREAD

**Issue by PiccioFra** [ScheiklP/sofa_env#18]
hi,
i have been running successfully a simulation in a new environment i have created myself... now that i have changed the meshes involved i am encountering this error though : 
[ERROR]   [FileRepository] File kidney-3786-0.01.comp NOT FOUND in :C:/Users/franc/anaconda3/envs/sofasource/sofa/src/share:C:/Users/franc/anaconda3/envs/sofasource/sofa/src/examples:C:/Users/franc/anaconda3/envs/sofasource/sofa/build:C:/Users/franc/anaconda3/envs/sofasource/sofa/build

actually this file is not in the right folder, but i have noticed that in C:/Users/franc/anaconda3/envs/sofasource/sofa/src/share there are the others .comp files of the previous meshes, without me having done anything.

how can i solve this problem? thanks in advance for your help

**Comment by ScheiklP** [comment]
Hi @PiccioFra ,
You are using a `PrecomputedConstraintCorrection` in your scene, right?
The error that you see is more of a warnging. SOFA says "I cannot find that file" but means "I cannot find that file, and I will create it for you, but that will take a minute."
https://github.com/ScheiklP/sofa_env?tab=readme-ov-file#notes

Cheers,
Paul
