### ISSUE TITLE
Units of measurements

### ISSUE THREAD

**Issue by PiccioFra** [ScheiklP/sofa_env#20]
Hi,

I would like to ask you what units of measurement are used in these environments as I haven't found anything in the documentation; 
in particular, I would like to know the unit of measurement used for Young's modulus.
Thanks 

Francesco

**Comment by ScheiklP** [comment]
Hi @PiccioFra,
that depends on the environment. Most environments are in mm/kg/s.
But for example the tissue retraction environment is in m/kg/s.
https://github.com/ScheiklP/sofa_env/blob/main/sofa_env/scenes/tissue_retraction/scene_description.py#L235

Cheers,
Paul
