### ISSUE TITLE
improve texture

### ISSUE THREAD

**Issue by PiccioFra** [ScheiklP/sofa_env#21]
Hi,
i'm using a .png image texture for the objects in my simulations, but  the image doesn't wrap around the mesh like i want and there's always a marked line that creates problems. There is a way to solve my problem in Sofa? or maybe to import the information about the texture mapping from another program?
thanks a lot

**Comment by ScheiklP** [comment]
Hi @PiccioFra ,
yes, you will have to use a separate software like Blender to correctly set the UV mapping for the `.obj` files.
For example something like this: https://www.youtube.com/watch?v=qa_1LjeWsJg
To convert an `.stl` to an `.obj` with UV data, you can look at https://github.com/ScheiklP/sofa_env/blob/main/docs/source/how-to/surface_meshes_blender.rst

You can also manually set the UV coordinates in the OglModel, but that is pretty annoying.
https://github.com/ScheiklP/sofa_env/blob/3c496f109955d7b2608091e26960db95f996b6d4/sofa_env/scenes/ligating_loop/sofa_objects/cavity.py#L279

Cheers,
Paul
