### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by Yangon0620** [ScheiklP/sofa_env#22]
I am following the [instructions](https://github.com/ScheiklP/sofa_env/blob/main/docs/source/setting_up_sofa.rst) to install SOFA and SofaPython3. When i`m building sofa with "cmake --build $FOLDER_TARGET -j --target install "  it came out "make: *** No rule to make target 'install'.  Stop." how to deal with it?

**Comment by ScheiklP** [comment]
Hi @Yangon0620 ,
did the previous cmake command 
```
cmake -Wno-dev \
-S $FOLDER_SRC -B $FOLDER_TARGET \
-DCMAKE_BUILD_TYPE=Release \
-DSOFA_FETCH_SOFAPYTHON3=OFF \
-DPLUGIN_SOFAPYTHON3=ON \
-DPython_EXECUTABLE=$PYTHON_EXE \
-DPython_ROOT_DIR=$PYTHON_ROOT_DIR \
-DSP3_LINK_TO_USER_SITE=ON \
-DSP3_PYTHON_PACKAGES_LINK_DIRECTORY=$PYTHON_PKG_PATH \
-DPLUGIN_SOFACARVING=ON \
-DSP3_BUILD_TEST=OFF \
-DSOFA_BUILD_TESTS=OFF
```
run without errors?

Cheers,
Paul

**Comment by Yangon0620** [comment]
Thanks for your help.
Indeed, there are errors when running the cmake. 
<pre>Sofa.Component.LinearSolver.Direct: DEPENDENCY metis NOT FOUND. SOFA_ALLOW_FETCH_DEPENDENCIES is ON, fetching metis...
CMake Error at /home/yangyang/sofa/build/_deps/metis-src/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.22 or higher is required.  You are running version 3.16.3


-- Configuring incomplete, errors occurred!
See also &quot;/home/yangyang/sofa/build/CMakeFiles/CMakeOutput.log&quot;.
See also &quot;/home/yangyang/sofa/build/CMakeFiles/CMakeError.log&quot;.</pre>

But when I update the Cmake version to 3.23.0 , it came out

 <pre>-- Sofa.GUI.Qt: Qt5Charts not found. No chart nor Profile will be compiled
<font color="#CC0000">CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):</font>
<font color="#CC0000">  Could not find a package configuration file provided by &quot;Qt5Charts&quot; with</font>
<font color="#CC0000">  any of the following names:</font>

<font color="#CC0000">    Qt5ChartsConfig.cmake</font>
<font color="#CC0000">    qt5charts-config.cmake</font>

<font color="#CC0000">  Add the installation prefix of &quot;Qt5Charts&quot; to CMAKE_PREFIX_PATH or set</font>
<font color="#CC0000">  &quot;Qt5Charts_DIR&quot; to a directory containing one of the above files.  If</font>
<font color="#CC0000">  &quot;Qt5Charts&quot; provides a separate development package or SDK, be sure it has</font>
<font color="#CC0000">  been installed.</font>
<font color="#CC0000">Call Stack (most recent call first):</font>
<font color="#CC0000">  cmake/Modules/FindQGLViewer.cmake:47 (find_package)</font>
<font color="#CC0000">  Sofa/GUI/Qt/CMakeLists.txt:77 (find_package)</font>


-- Configuring incomplete, errors occurred!
See also &quot;/home/yangyang/sofa/build/CMakeFiles/CMakeOutput.log&quot;.
See also &quot;/home/yangyang/sofa/build/CMakeFiles/CMakeError.log&quot;.
</pre>

It seems like the QT5chart is lacked on my computer, so I install the libqt5charts5. Then, the Cmake done with warnings

<pre>-- Configuring done
<font color="#C4A000">CMake Warning at /usr/local/share/cmake-3.23/Modules/FindPython/Support.cmake:3331 (add_library):</font>
<font color="#C4A000">  Cannot generate a safe runtime search path for target Bindings.SofaExporter</font>
<font color="#C4A000">  because files in some directories may conflict with libraries in implicit</font>
<font color="#C4A000">  directories:</font>

<font color="#C4A000">    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:</font>
<font color="#C4A000">      /home/yangyang/miniconda3/envs/sofa/lib</font>

<font color="#C4A000">  Some of these libraries may not be found correctly.</font>
<font color="#C4A000">Call Stack (most recent call first):</font>
<font color="#C4A000">  /usr/local/share/cmake-3.23/Modules/FindPython.cmake:580 (__Python_add_library)</font>
<font color="#C4A000">  applications/plugins/SofaPython3/CMake/SofaPython3Tools.cmake:120 (python_add_library)</font>
<font color="#C4A000">  applications/plugins/SofaPython3/bindings/SofaExporter/CMakeLists.txt:18 (SP3_add_python_module)</font>


-- Generating done
-- Build files have been written to: /home/yangyang/sofa/build
</pre>
Is there something wrong?

**Comment by ScheiklP** [comment]
Hi @Yangon0620 ,
the output looks fine now.
Does compiling work now?

Cheers,
Paul

**Comment by Yangon0620** [comment]
Thanks, the compile works.  But when the compiling reached 49% of the progress, something went wrong and the system crashed, and I made it twice.  Maybe I need to download the compiled version directly, I think.  Is there some thing I should be careful when using the compiled version in conda environment? I guess maybe the right way is to git clone the compiled sofa framework in conda sofa environment where the python shown in the [instructions](https://github.com/ScheiklP/sofa_env/blob/main/docs/source/setting_up_sofa.rst) is well installed

**Comment by Yangon0620** [comment]
I tried to compile again with -j2,  the compiling succeed!
