### ISSUE TITLE
Running test error with "SIG 11 - SIGSEGV: segfault"

### ISSUE THREAD

**Issue by Yangon0620** [ScheiklP/sofa_env#24]
Hi, I`m running the test scripts with "python3 sofa_env/scenes/controllable_object_example/controllable_env.py". I can see a red ball and blue soft board. When the red ball slid off the board, the process crashed whit the SIG 11.  Here is the whole log:
<pre>---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: /home/yangyang/sofa/build/install
---------------------------------------
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Topology.Container.Constant.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.LinearSolver.Iterative.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Topology.Container.Grid.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Constraint.Lagrangian.Solver.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.SolidMechanics.FEM.Elastic.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Mapping.NonLinear.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/plugins/ArticulatedSystemPlugin/lib/libArticulatedSystemPlugin.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Collision.Detection.Intersection.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.LinearSolver.Direct.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Mass.so
<font color="#C4A000">[DEPRECATED] </font><font color="#3465A4">[SofaBoundaryCondition] </font>SofaBoundaryCondition is deprecated. It will be removed at v23.06. You may use Sofa.Component.Constraint.Projective and Sofa.Component.MechanicalLoad instead.
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Constraint.Projective.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.MechanicalLoad.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/collections/SofaBoundaryCondition/lib/libSofaBoundaryCondition.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Collision.Detection.Algorithm.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Setting.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.SceneUtility.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.IO.Mesh.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Collision.Response.Contact.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.SolidMechanics.Spring.so
<font color="#C4A000">[DEPRECATED] </font><font color="#3465A4">[SofaEngine] </font>SofaEngine is deprecated. It will be removed at v23.06. Use Sofa.Component.Engine.Select instead.
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Engine.Select.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/collections/SofaEngine/lib/libSofaEngine.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.ODESolver.Backward.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.AnimationLoop.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Constraint.Lagrangian.Correction.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Visual.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Constraint.Lagrangian.Model.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Collision.Geometry.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.ODESolver.Forward.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.GL.Component.Rendering3D.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Topology.Mapping.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.GL.Component.Shader.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Mapping.Linear.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.StateContainer.so
<font color="#8AE234">[INFO]    </font><font color="#3465A4">[PluginManager] </font>Loaded plugin: /home/yangyang/sofa/build/install/lib/libSofa.Component.Topology.Container.Dynamic.so
<font color="#FCE94F">[WARNING] </font><font color="#3465A4">[MechanicalObject(unnamed)] </font>Could not read value for data field showColor: 255 0 255 
<font color="#FCE94F">[WARNING] </font><font color="#3465A4">[BoxROI(BoxROI)] </font>No rest position yet defined. Box might not work properly. 
This may be caused by an early call of init() on the box before  
the mesh or the MechanicalObject of the node was initialized too
<font color="#FCE94F">[WARNING] </font><font color="#3465A4">[MeshOBJLoader(unnamed)] </font>Could not read value for data field handleSeams: None
<font color="#FCE94F">[WARNING] </font><font color="#3465A4">[InteractiveCamera(camera)] </font>Too many missing parameters ; taking default ...
<font color="#FCE94F">[WARNING] </font><font color="#3465A4">[CGLinearSolver(CGLinearSolver)] </font>denominator threshold reached at first iteration of CG  
Check the &apos;threshold&apos; data field, you might decrease it

########## SIG 11 - SIGSEGV: segfault ##########
  sofa::helper::BackTrace::sig(int)
  PyErr_Fetch
  on_exit+0
  __libc_start_main
Segmentation fault (core dumped)
</pre>
Is the "SIG 11 - SIGSEGV : segfault" normal? If not, what`s wrong with this process?
looking forward to your replay, thanks

**Comment by ScheiklP** [comment]
Hi @Yangon0620 ,
yes that was the normal behavior.
The SIG 11 happened after the env was done.
I added a fix to the baseclass that now correctly unloads the simulation, when closing the env.
https://github.com/ScheiklP/sofa_env/commit/2f0020d18f135118adfee179670793111e2a9e21

Thanks for noticing! :)

Cheers,
Paul
