### ISSUE TITLE
No output for tissue retraction environment scene description

### ISSUE THREAD

**Issue by saketh2002** [ScheiklP/sofa_env#27]
Hi,
I am trying to run scene_description.py file for tissue retraction environment, however I am getting following error for runSofa 
[ERROR]   [FileRepository] File tissue-1479-0.01.comp NOT FOUND in :/home/saketh/SOFA/v23.06.00/share/sofa:/home/saketh/SOFA/v23.06.00/share/sofa/examples:/home/saketh/SOFA/v23.06.00/share/sofa:/home/saketh/SOFA/v23.06.00/share/sofa/examples
I am running it it 23.06.00 , is the version of sofa a potential problem ?
![Screenshot from 2024-05-25 23-00-54](https://github.com/ScheiklP/sofa_env/assets/65168029/2c444457-45b3-4bdc-8be9-748f683217cc)

**Comment by ScheiklP** [comment]
Hi @saketh2002 ,
see https://github.com/ScheiklP/sofa_env?tab=readme-ov-file#notes :).

Cheers,
Paul
