### ISSUE TITLE
[ERROR]   [SofaRuntime] ValueError: Object type BackgroundSetting<> was not created   The object 'BackgroundSetting' is not in the factory.   This component has been MOVED from SofaBaseVisual to Sofa.Component.UserInterface.ConfigurationSetting since SOFA v22.06. To continue using this component you may need to update your scene by adding <RequiredPlugin name='Sofa.Component.UserInterface.ConfigurationSetting'/>    Traceback (most recent call last):   File "/home/grize/PycharmProjects/sofa_env/sofa_env/scenes/controllable_object_example/controllable_env.py", line 66, in <module>     env.reset()   File "/home/grize/PycharmProjects/sofa_env/sofa_env/scenes/controllable_object_example/controllable_env.py", line 53, in reset     return super().reset(seed)   File "/home/grize/PycharmProjects/sofa_env/sofa_env/base.py", line 207, in reset     self._init_sim()   File "/home/grize/PycharmProjects/sofa_env/sofa_env/base.py"

### ISSUE THREAD

**Issue by Grizemc** [ScheiklP/sofa_env#34]
[ERROR]   [SofaRuntime] ValueError: Object type BackgroundSetting<> was not created  
The object 'BackgroundSetting' is not in the factory.  
This component has been MOVED from SofaBaseVisual to Sofa.Component.UserInterface.ConfigurationSetting since SOFA v22.06.
To continue using this component you may need to update your scene by adding
<RequiredPlugin name='Sofa.Component.UserInterface.ConfigurationSetting'/>  

Traceback (most recent call last):
  File "/home/grize/PycharmProjects/sofa_env/sofa_env/scenes/controllable_object_example/controllable_env.py", line 66, in <module>
    env.reset()
  File "/home/grize/PycharmProjects/sofa_env/sofa_env/scenes/controllable_object_example/controllable_env.py", line 53, in reset
    return super().reset(seed)
  File "/home/grize/PycharmProjects/sofa_env/sofa_env/base.py", line 207, in reset
    self._init_sim()
  File "/home/grize/PycharmProjects/sofa_env/sofa_env/base.py", line 286, in _init_sim
    self.scene_creation_result = getattr(self._scene_description_module, "createScene")(self._sofa_root_node, **self.create_scene_kwargs)
  File "/home/grize/PycharmProjects/sofa_env/sofa_env/scenes/controllable_object_example/scene_description.py", line 23, in createScene
    root_node.addObject("BackgroundSetting", color=(1.0, 1.0, 1.0, 1.0))

**Comment by ScheiklP** [comment]
Hi @Grizemc ,
I would appreciate some additional context. :D 

However, you are lucky; I already fixed this error in a recent commit https://github.com/ScheiklP/sofa_env/commit/d58030a3f54bf9cdd15cdb8cdf61d5a83cb6c802 .

Please pull the recent version of sofa_env and try again.

Cheers,
Paul

**Comment by Grizemc** [comment]
thank you very much！

**Comment by sese1815** [comment]
I've recently run into a similar issue.
After installing SOFA_env and SOFA (85bf7e05dd088b824794dda0046679df13b13e6e) and trying the test script i get this error.
python3 ./sofa_env/scenes/controllable_object_example/controllable_env.py
```

[ERROR]   [SofaRuntime] ValueError: Object type BackgroundSetting<> was not created  
The object 'BackgroundSetting' is not in the factory.  
This component has been MOVED from SofaBaseVisual to Sofa.Component.UserInterface.ConfigurationSetting since SOFA v22.06.
To continue using this component you may need to update your scene by adding
<RequiredPlugin name='Sofa.Component.UserInterface.ConfigurationSetting'/>  

Traceback (most recent call last):
  File "/home/das/sofa/sofa_env/./sofa_env/scenes/controllable_object_example/controllable_env.py", line 66, in <module>
    env.reset()
  File "/home/das/sofa/sofa_env/./sofa_env/scenes/controllable_object_example/controllable_env.py", line 53, in reset
    return super().reset(seed)
  File "/home/das/sofa/sofa_env/sofa_env/base.py", line 207, in reset
    self._init_sim()
  File "/home/das/sofa/sofa_env/sofa_env/base.py", line 286, in _init_sim
    self.scene_creation_result = getattr(self._scene_description_module, "createScene")(self._sofa_root_node, **self.create_scene_kwargs)
  File "/home/das/sofa/sofa_env/sofa_env/scenes/controllable_object_example/scene_description.py", line 21, in createScene
    add_scene_header(
  File "/home/das/sofa/sofa_env/sofa_env/sofa_templates/scene_header.py", line 172, in add_scene_header
    root_node.addObject("BackgroundSetting", color=background_color)

```
while looking for a solution i found this issue and checked your solution but this does seem to a have already been applied 
From my scene_header file SCENE_HEADER_PLUGIN_LIST = [
    "Sofa.Component.SceneUtility",  # <- [RequiredPlugin]
    "Sofa.Component.AnimationLoop",  # <- [FreeMotionAnimationLoop]
    "Sofa.Component.Collision.Detection.Algorithm",  # <- [BVHNarrowPhase, BruteForceBroadPhase, DefaultPipeline]
    "Sofa.Component.Collision.Response.Contact",  # <- Needed to use components [DefaultContactManager]
    "Sofa.Component.Collision.Detection.Intersection",  # <- [NewProximityIntersection]
    "Sofa.Component.Constraint.Lagrangian.Solver",  # <- [LCPConstraintSolver]
    "Sofa.Component.Visual",  # <- [VisualStyle]
    "Sofa.Component.Setting",  # <- [BackgroundSetting]
]
if there is anything i should try or you would like to know feel free to let me know
Any help is appreciated
