### ISSUE TITLE
sofa_env/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py     It didn't work

### ISSUE THREAD

**Issue by Grizemc** [ScheiklP/sofa_env#35]
1.I encountered the following error while running the ”gras_lift_toucheenv.py” script, but I was successful when running the controllable-env.py script：
sofa::simulation::ResetVisitor::processNodeTopDown(sofa::simulation::Node*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::doExecuteVisitor(sofa::simulation::Visitor*, bool)
  sofa::simulation::node::reset(sofa::simulation::Node*)
  _PyObject_MakeTpCall
  _PyEval_EvalFrameDefault
  _PyEval_EvalFrameDefault
  _PyFunction_Vectorcall
  _PyEval_EvalFrameDefault
  PyEval_EvalCode
  _PyRun_SimpleFileObject
  _PyRun_AnyFileObject
  Py_RunMain
  Py_BytesMain
  __libc_start_main
段错误 (核心已转储)

2. Meanwhile, I followed the sofa_godot tutorial, but encountered the following error while loading and compiling in the plugin:
[INFO]    [GUIManager] Registered qt as a GUI.
[INFO]    [PluginManager] Loaded plugin: /home/grize/sofa/build/install/lib/libSofa.GUI.Qt.so
[INFO]    [PluginManager] Loaded plugin: /home/grize/sofa/build/install/plugins/MultiThreading/lib/libMultiThreading.so
[INFO]    [PluginManager] Loaded plugin: /home/grize/sofa/build/install/plugins/Sofa.Metis/lib/libSofa.Metis.so
[INFO]    [PluginManager] 70 plugins have been loaded from /home/grize/sofa/build/install/lib/plugin_list.conf
[INFO]    [GUIManager] lastUsedGUI.ini not found; using default GUI.
[WARNING] [Qt] Could not find the Qt platform plugin "xcb" in ""

**Comment by Grizemc** [comment]
But in my environment, it is possible to find xcb:
(sofa)  grize@grize-MS-7D90 :~/PycharmProjects/lap_gym-main$ find / -name "libqxcb.so" 2>/dev/null
/opt/nvidia/nsight-systems/2023.4.4/host-linux-x64/Plugins/platforms/libqxcb.so
/opt/nvidia/nsight-compute/2024.1.0/host/linux-desktop-glibc_2_11_3-x64/Plugins/platforms/libqxcb.so
/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
/home/grize/PycharmProjects/sofa_env/SOFA/bin/platforms/libqxcb.so
/home/grize/PycharmProjects/sofa_env1/1/sofa_env/SOFA/bin/platforms/libqxcb.so
/home/grize/PycharmProjects/lap_gym-main/sofa_env/SOFA/bin/platforms/libqxcb.so
/home/grize/sofa/build/install_yuan/bin/platforms/libqxcb.so
/home/grize/sofa/build/install/bin/libqxcb.so
/home/grize/sofa/build/install/bin/platforms/libqxcb.so
/home/grize/anaconda3/plugins/platforms/libqxcb.so
/home/grize/anaconda3/envs/surrol/lib/python3.7/site-packages/cv2/qt/plugins/platforms/libqxcb.so
/home/grize/anaconda3/envs/sofa/lib/libqxcb.so
/home/grize/anaconda3/envs/sofa/lib/python3.10/site-packages/cv2/qt/plugins/platforms/libqxcb.so
/home/grize/anaconda3/pkgs/qt-main-5.15.2-h53bd1ea_10/plugins/platforms/libqxcb.so
/home/grize/.local/share/Trash/files/SOFA_v24.3.06.00_Linux/bin/platforms/libqxcb.so

**Comment by ScheiklP** [comment]
Hi @Grizemc ,
indeed, there a recent update of SOFA seems to have broken my code for ArticulatedSystemMapping. I will have to look into that.

For SofaGodot, I am currently not maintaining it actively.

**Comment by Grizemc** [comment]
Thank you very much! May I ask if I need to lower the version of SOFA to recompile it so that Gras_lift_touchenv.py can function.

**Comment by Grizemc** [comment]
> 你好@Grizemc确实 ，SOFA 的最近一次更新似乎破坏了我的 ArticulatedSystemMapping 代码。我必须调查一下。
> 
> 对于 SofaGodot，我目前没有积极维护它。

Thank you very much! May I ask if I need to lower the version of SOFA to recompile it so that Gras_lift_touchenv.py can function.

**Comment by ScheiklP** [comment]
That would probably do as a workaround. :)

You could try going back through the major releases (23.12, 23.06, 22.12, ...).
I think 23.12 should work.

**Comment by Grizemc** [comment]
Sorry to bother you again, but as a reference, I tried compiling versions 23.12, 23.06, and 22.12 of the sofa, but Gras_limit_touchenv.py always reported an error:
sofa::simulation::ResetVisitor::processNodeTopDown(sofa::simulation::Node*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::doExecuteVisitor(sofa::simulation::Visitor*, bool)
sofa::simulation::node::reset(sofa::simulation::Node*)
_PyObject_MakeTpCall
_PyEval_EvalFrameDefault
_PyEval_EvalFrameDefault
_PyFunction_Vectorcall
_PyEval_EvalFrameDefault
PyEval_EvalCode
_PyRun_SimpleFileObject
_PyRun_AnyFileObject
Py_RunMain
Py_BytesMain
__libc_start_main
Duan error (core has been dumped)

**Comment by Grizemc** [comment]
> That would probably do as a workaround. :)
> 
> You could try going back through the major releases (23.12, 23.06, 22.12, ...). I think 23.12 should work.

Hello, may I ask how to solve the problem of some scene scripts not running due to Sofa updates?

**Comment by Zoniaku** [comment]
Hey! @Grizemc **I am having the same issue**, well to me most scenes are kinda broken. are you compiling sofa in linux or ubuntu? also how are you sure its due to the sofa version. is there an error log that shows this?

**Comment by ScheiklP** [comment]
Hi @Zoniaku,
yeah, sorry. The update to downloading a precompiled SOFA version was a bit hasty.
A workaround would be rolling back to an earlier version of sofa_env together with manually compiling sofa.
For example this one: https://github.com/ScheiklP/sofa_env/commit/d58030a3f54bf9cdd15cdb8cdf61d5a83cb6c802

**Comment by Grizemc** [comment]
> 嘿！@Grizemc **我遇到了同样的问题**，对我来说大多数场景都有点不完整。你是在 Linux 还是 ubuntu 中编译 sofa？另外你怎么确定这是由于 sofa 版本造成的？有没有显示此问题的错误日志？

Hello, have you implemented it according to the author's statement? Has it been successful？

**Comment by Grizemc** [comment]
> Hi @Zoniaku, yeah, sorry. The update to downloading a precompiled SOFA version was a bit hasty. A workaround would be rolling back to an earlier version of sofa_env together with manually compiling sofa. For example this one: [d58030a](https://github.com/ScheiklP/sofa_env/commit/d58030a3f54bf9cdd15cdb8cdf61d5a83cb6c802)

May I ask again, which versions of Sofa_env, Sofa, and Sofa_Python 3 can successfully run most of the scripts in Sofa_env, and what are the specific commits for these three versions.
Because I used your https://github.com/ScheiklP/sofa_env/blob/d0d197d4bda74338e8b6aa1e5a72a9c715f7f73e/docs/source/setting_up_sofa.rst All the explanations,
Multiple versions of sofa_env were used separately,
And the e74b94848af09536873d1c7eb291a5e742fc6077 and e41f341feb82351c00a0b9b7b94e9035a389e346 versions of sofa were used,
Sofapython version 15bc9725e85b282ce97738266e9849ca1b9c1602, but ultimately running: cmake Wno dev\
-S $FOLDER_SRC -B $FOLDER_TARGET \
-DCMAKE_BUILD_TYPE=Release \
-DSOFA_FETCH_SOFAPYTHON3=OFF \
-DPLUGIN_SOFAPYTHON3=ON \
-DPython_EXECUTABLE=$PYTHON_EXE \
-DPython_ROOT_DIR=$PYTHON_ROOT_DIR \
-DSP3_LINK_TO_USER_SITE=ON \
-DSP3_PYTHON_PACKAGES_LINK_DIRECTORY=$PYTHON_PKG_PATH \
-DPLUGIN_SOFACARVING=ON \
-DSP3_BUILD_TEST=OFF \
-DSOFA_BUILD_TEST=OFF all display:
-- Adding plugin ArticulatedSystemPlugin
-- Adding plugin SofaCarving
-- Adding plugin SofaMatrix
-- Adding application SceneChecking
-- Adding application runSofa
Write Plugin list at /home/grize/sofa/build/lib/plugin_list.conf.default
-- Configuring done
CMake Warning at applications/plugins/SofaMatrix/CMakeLists.txt:79 (add_library):
Cannot generate a safe runtime search path for target SofaMatrix because
files in some directories may conflict with libraries in implicit
directories:
runtime library [libtiff.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
runtime library [libpng16.so.16] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
Some of these libraries may not be found correctly.
CMake Warning at applications/projects/runSofa/CMakeLists.txt:58 (add_executable):
Cannot generate a safe runtime search path for target runSofa because files
in some directories may conflict with libraries in implicit directories:
runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
Some of these libraries may not be found correctly.
-- Generating done
-- Build files have been written to: /home/grize/sofa/build
II Sometimes it may also display:
-DSP3_LINK_TO_USER_SITE=ON \
-DSP3_PYTHON_PACKAGES_LINK_DIRECTORY=$PYTHON_PKG_PATH \
-DPLUGIN_SOFACARVING=ON \ Some modules are useless
And sometimes when I use compiled binary files, such as versions 23.06, 22.12, etc., I get an error saying: sofa. helper
can't find.
So can you provide specific requirements for solving the scenario script running problem, including the three versions of Sofa, and whether to compile directly from source code or use pre compiled binary files. Can Windows be solved with WSL

**Comment by Grizemc** [comment]
> Hi @Zoniaku, yeah, sorry. The update to downloading a precompiled SOFA version was a bit hasty. A workaround would be rolling back to an earlier version of sofa_env together with manually compiling sofa. For example this one: [d58030a](https://github.com/ScheiklP/sofa_env/commit/d58030a3f54bf9cdd15cdb8cdf61d5a83cb6c802)

May I ask again, which versions of Sofa_env, Sofa, and Sofa_Python 3 can successfully run most of the scripts in Sofa_env, and what are the specific commits for these three versions.
Because I used your https://github.com/ScheiklP/sofa_env/blob/d0d197d4bda74338e8b6aa1e5a72a9c715f7f73e/docs/source/setting_up_sofa.rst All the explanations,
Multiple versions of sofa_env were used separately,
And the e74b94848af09536873d1c7eb291a5e742fc6077 and e41f341feb82351c00a0b9b7b94e9035a389e346 versions of sofa were used,
Sofapython version 15bc9725e85b282ce97738266e9849ca1b9c1602, but ultimately running: cmake Wno dev\
-S $FOLDER_SRC -B $FOLDER_TARGET \
-DCMAKE_BUILD_TYPE=Release \
-DSOFA_FETCH_SOFAPYTHON3=OFF \
-DPLUGIN_SOFAPYTHON3=ON \
-DPython_EXECUTABLE=$PYTHON_EXE \
-DPython_ROOT_DIR=$PYTHON_ROOT_DIR \
-DSP3_LINK_TO_USER_SITE=ON \
-DSP3_PYTHON_PACKAGES_LINK_DIRECTORY=$PYTHON_PKG_PATH \
-DPLUGIN_SOFACARVING=ON \
-DSP3_BUILD_TEST=OFF \
-DSOFA_BUILD_TEST=OFF all display:
-- Adding plugin ArticulatedSystemPlugin
-- Adding plugin SofaCarving
-- Adding plugin SofaMatrix
-- Adding application SceneChecking
-- Adding application runSofa
Write Plugin list at /home/grize/sofa/build/lib/plugin_list.conf.default
-- Configuring done
CMake Warning at applications/plugins/SofaMatrix/CMakeLists.txt:79 (add_library):
Cannot generate a safe runtime search path for target SofaMatrix because
files in some directories may conflict with libraries in implicit
directories:
runtime library [libtiff.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
runtime library [libpng16.so.16] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
Some of these libraries may not be found correctly.
CMake Warning at applications/projects/runSofa/CMakeLists.txt:58 (add_executable):
Cannot generate a safe runtime search path for target runSofa because files
in some directories may conflict with libraries in implicit directories:
runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
Some of these libraries may not be found correctly.
-- Generating done
-- Build files have been written to: /home/grize/sofa/build
II Sometimes it may also display:
-DSP3_LINK_TO_USER_SITE=ON \
-DSP3_PYTHON_PACKAGES_LINK_DIRECTORY=$PYTHON_PKG_PATH \
-DPLUGIN_SOFACARVING=ON \ Some modules are useless
And sometimes when I use compiled binary files, such as versions 23.06, 22.12, etc., I get an error saying: sofa. helper
can't find.
So can you provide specific requirements for solving the scenario script running problem, including the three versions of Sofa, and whether to compile directly from source code or use pre compiled binary files. Can Windows be solved with WSL?
esteem it  a favor! The stars have already been lit up hahaha

**Comment by Grizemc** [comment]
May I ask again, which versions of Sofa_env, Sofa, and Sofa_Python 3 can successfully run most of the scripts in Sofa_env, and what are the specific commits for these three versions.
Because I used your https://github.com/ScheiklP/sofa_env/blob/d0d197d4bda74338e8b6aa1e5a72a9c715f7f73e/docs/source/setting_up_sofa.rst All the explanations,
Multiple versions of sofa_env were used separately,
And the e74b94848af09536873d1c7eb291a5e742fc6077 and e41f341feb82351c00a0b9b7b94e9035a389e346 versions of sofa were used,
Sofapython version 15bc9725e85b282ce97738266e9849ca1b9c1602, but ultimately running: cmake Wno dev\
-S $FOLDER_SRC -B $FOLDER_TARGET \
-DCMAKE_BUILD_TYPE=Release \
-DSOFA_FETCH_SOFAPYTHON3=OFF \
-DPLUGIN_SOFAPYTHON3=ON \
-DPython_EXECUTABLE=$PYTHON_EXE \
-DPython_ROOT_DIR=$PYTHON_ROOT_DIR \
-DSP3_LINK_TO_USER_SITE=ON \
-DSP3_PYTHON_PACKAGES_LINK_DIRECTORY=$PYTHON_PKG_PATH \
-DPLUGIN_SOFACARVING=ON \
-DSP3_BUILD_TEST=OFF \
-DSOFA_BUILD_TEST=OFF all display:
-- Adding plugin ArticulatedSystemPlugin
-- Adding plugin SofaCarving
-- Adding plugin SofaMatrix
-- Adding application SceneChecking
-- Adding application runSofa
Write Plugin list at /home/grize/sofa/build/lib/plugin_list.conf.default
-- Configuring done
CMake Warning at applications/plugins/SofaMatrix/CMakeLists.txt:79 (add_library):
Cannot generate a safe runtime search path for target SofaMatrix because
files in some directories may conflict with libraries in implicit
directories:
runtime library [libtiff.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
runtime library [libpng16.so.16] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
Some of these libraries may not be found correctly.
CMake Warning at applications/projects/runSofa/CMakeLists.txt:58 (add_executable):
Cannot generate a safe runtime search path for target runSofa because files
in some directories may conflict with libraries in implicit directories:
runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/grize/anaconda3/lib
Some of these libraries may not be found correctly.
-- Generating done
-- Build files have been written to: /home/grize/sofa/build

II Sometimes it may also display:
-DSP3_LINK_TO_USER_SITE=ON \
-DSP3_PYTHON_PACKAGES_LINK_DIRECTORY=$PYTHON_PKG_PATH \
-DPLUGIN_SOFACARVING=ON \ Some modules are useless

And sometimes when I use compiled binary files, such as versions 23.06, 22.12, etc., I get an error saying: sofa. helper
can't find.

So can you provide specific requirements for solving the scenario script running problem, including the three versions of Sofa, and whether to compile directly from source code or use pre compiled binary files. Can Windows be solved with WSL?
esteem it  a favor! The stars have already been lit up hahaha

**Comment by ScheiklP** [comment]
Hi @Grizemc ,
could you check out the most recent commit? I think I fixed all scenes except for TissueManipulation.

**Comment by Grizemc** [comment]
Thank you very much, you are truly an outstanding author!

However, every time I compile Sofa and Sofapython3 using cmake, the result is that there is no SP3 in the path/home/drivewz/Sofa/build/install/plugins. This means that my cmake did not compile sp3, right?, Therefore, when I used your newly submitted commit script, I separately used pre compiled files (including the total pre compilation of Sofa and Sofapython3), as well as my own compiled Sofa+pre compiled sp3 (because I did not compile sp3 when I compiled it myself), and I switched from dual system to WSL under Windows, using the same process as instructions. Sofa source code used v23.12, sp3 used f1ac0f03efd6f6e7c30df8b18259e16da523f0b2.

But the script, for example: gras_lift_touch_cenv.py, always outputs:

[WARNING] [InteractiveCamera(camera)] Too many missing parameters ;  taking default ...
[WARNING] [MechanicalObject(unnamed)] Could not read value for data field showColor: 255 0 255 
[WARNING] [MechanicalObject(unnamed)] Could not read value for data field showColor: 255 0 255 
[ERROR]   [SofaRuntime] ValueError: Object type StopperLagrangianConstraint<> was not created  
The object 'StopperLagrangianConstraint' is not in the factory.  
But the following exits:  
: StopperConstraint (77% match)  
: BilateralInteractionConstraint (63% match)  
: UnilateralInteractionConstraint (62% match)  
: ParabolicConstraint (60% match)  
: FixedTranslationConstraint (60% match)  
Traceback (most recent call last):
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py", line 820, in <module>
env.reset()
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py", line 480, in reset
super().reset(seed)
File "/home/grizewz/sofa_env/sofa_env/base.py", line 207, in reset
self._init_sim()
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py", line 418, in _init_sim
super()._init_sim()
File "/home/grizewz/sofa_env/sofa_env/base.py", line 286, in _init_sim
self.scene_creation_result = getattr(self._scene_description_module, "createScene")(self._sofa_root_node, **self.create_scene_kwargs)
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/scene_description.py", line 165, in createScene
gripper = Gripper(
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/sofa_objects/gripper.py", line 95, in __init__
PivotizedArticulatedInstrument.__init__(
File "/home/grizewz/sofa_env/sofa_env/sofa_templates/rigid.py", line 1122, in __init__
super().__init__(
File "/home/grizewz/sofa_env/sofa_env/sofa_templates/rigid.py", line 773, in __init__
self.articulation_description_node.addObject(

Then, I observed your newly updated script and found that you did indeed include StopperLagrangian Constraint in the updated script.

Therefore, I believe that the versions of Sofa and SP3 are incorrect.
At the same time, may I ask if you use pre compiled files or manually compiled sofa and sp3 when running most of the scripts successfully? If you compiled it manually, could you give me some advice as my SP3 was not compiled in the build file.

**Comment by Grizemc** [comment]
Hi@ScheiklP 
Thank you very much, you are truly an outstanding author!

However, every time I compile Sofa and Sofapython3 using cmake, the result is that there is no SP3 in the path/home/drivewz/Sofa/build/install/plugins. This means that my cmake did not compile sp3, right?, Therefore, when I used your newly submitted commit script, I separately used pre compiled files (including the total pre compilation of Sofa and Sofapython3), as well as my own compiled Sofa+pre compiled sp3 (because I did not compile sp3 when I compiled it myself), and I switched from dual system to WSL under Windows, using the same process as instructions. Sofa source code used v23.12, sp3 used f1ac0f03efd6f6e7c30df8b18259e16da523f0b2.

But the script, for example: gras_lift_touch_cenv.py, always outputs:

[WARNING] [InteractiveCamera(camera)] Too many missing parameters ; taking default ...
[WARNING] [MechanicalObject(unnamed)] Could not read value for data field showColor: 255 0 255
[WARNING] [MechanicalObject(unnamed)] Could not read value for data field showColor: 255 0 255
[ERROR] [SofaRuntime] ValueError: Object type StopperLagrangianConstraint<> was not created
The object 'StopperLagrangianConstraint' is not in the factory.
But the following exits:
: StopperConstraint (77% match)
: BilateralInteractionConstraint (63% match)
: UnilateralInteractionConstraint (62% match)
: ParabolicConstraint (60% match)
: FixedTranslationConstraint (60% match)
Traceback (most recent call last):
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py", line 820, in
env.reset()
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py", line 480, in reset
super().reset(seed)
File "/home/grizewz/sofa_env/sofa_env/base.py", line 207, in reset
self._init_sim()
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py", line 418, in _init_sim
super()._init_sim()
File "/home/grizewz/sofa_env/sofa_env/base.py", line 286, in _init_sim
self.scene_creation_result = getattr(self._scene_description_module, "createScene")(self._sofa_root_node, **self.create_scene_kwargs)
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/scene_description.py", line 165, in createScene
gripper = Gripper(
File "/home/grizewz/sofa_env/sofa_env/scenes/grasp_lift_touch/sofa_objects/gripper.py", line 95, in init
PivotizedArticulatedInstrument.init(
File "/home/grizewz/sofa_env/sofa_env/sofa_templates/rigid.py", line 1122, in init
super().init(
File "/home/grizewz/sofa_env/sofa_env/sofa_templates/rigid.py", line 773, in init
self.articulation_description_node.addObject(

Then, I observed your newly updated script and found that you did indeed include StopperLagrangian Constraint in the updated script.

Therefore, I believe that the versions of Sofa and SP3 are incorrect.
At the same time, may I ask if you use pre compiled files or manually compiled sofa and sp3 when running most of the scripts successfully? If you compiled it manually, could you give me some advice as my SP3 was not compiled in the build file.

**Comment by Grizemc** [comment]
@ScheiklP I apologize for bothering you again. I successfully ran your newly submitted project using the pre compiled 24.06 sofa file, but the only question that puzzled me was:
1. I ran it directly in the PyCharm window and successfully reproduced the expected window!

2. I executed it with the command line and received an error message:
[INFO]    [PluginManager] Loaded plugin: /home/grize/sofa/build/install/lib/libSofa. Component.ODESolver.Forward.so
[DEPRECATED] [SofaGeneralRigid] SofaGeneralRigid is being deprecated.  It will be removed at v23.06. You may use Sofa.Component.Mapping instead.
[INFO]    [PluginManager] Loaded plugin: /home/grize/sofa/build/install/lib/libSofa. Component.Mapping.so
[INFO]    [PluginManager] Loaded plugin: /home/grize/sofa/build/install/collections/SofaGeneralRigid/lib/libSofaGeneralRigid.so
[WARNING] [InteractiveCamera(camera)] Too many missing parameters ;  taking default ...
[WARNING] [MechanicalObject(unnamed)] Could not read value for data field showColor: 255 0 255 
[WARNING] [MechanicalObject(unnamed)] Could not read value for data field showColor: 255 0 255 
[ERROR]   [SofaRuntime] TypeError: Gripper.__ init__() got an unexpected keyword argument 'ptsd_reset_noise'
Traceback (most recent call last):
File "/home/grize/PycharmProjects/sofa_env-main/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py", line 820, in <module>
env.reset()
File "/home/grize/PycharmProjects/sofa_env-main/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py", line 480, in reset
super().reset(seed)
File "/home/grize/PycharmProjects/sofa_env/sofa_env/base.py", line 206, in reset
self._init_sim()
File "/home/grize/PycharmProjects/sofa_env-main/sofa_env/scenes/grasp_lift_touch/grasp_lift_touch_env.py", line 418, in _init_sim
super()._init_sim()
File "/home/grize/PycharmProjects/sofa_env/sofa_env/base.py", line 280, in _init_sim
self.scene_creation_result = getattr(self._scene_description_module, "createScene")(self._sofa_root_node, **self.create_scene_kwargs)
File "/home/grize/PycharmProjects/sofa_env-main/sofa_env/scenes/grasp_lift_touch/scene_description.py", line 165, in createScene
gripper = Gripper(

I am very curious about this situation; do you have any suggestions if possible? However, I have successfully reproduced the result, and I'm just puzzled by this situation.

Lastly, based on your information, I guess you might be from Germany. The last person who made me feel such a profound sense of rigor and sincerity in science was also a German scholar, which further deepened my admiration for your country's academic atmosphere, full of scientific rigor. Your dedication to scholarship has profoundly inspired me as someone who has just entered graduate school.

Once again, thank you for demonstrating your sincere and rigorous sense of responsibility!

**Comment by ScheiklP** [comment]
Hi @Grizemc ,
my best guess for the second one is that SOFA tries to guess where it can find the binaries for SOFA, and comes up with the wrong guess.
You could
```
export SOFA_ROOT=<path-to-sofa-env>/SOFA 
export SOFAPYTHON3_ROOT=<path-to-sofa-env>/SOFA/plugins/SofaPython3 
```
in your command line, before running an env. This will tell SOFA, where to look for the correct binaries.

Cheers,
Paul

**Comment by Grizemc** [comment]
Due to my multiple attempts, I overlooked this. Thank you again!
